version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "12qwaszx"
    ports:
      - "15432:5432"
    volumes:
      - /home/renatogroffe/Desenvolvimento/Docker-Compose/PostgreSQL:/var/lib/postgresql/data 
    networks:
      - postgres-compose-network
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "wagner.costa.oliveira@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "12qwaszx"
    ports:
      - "16543:80"
    depends_on:
      - teste-postgres-compose
    networks:
      - postgres-network

networks: 
  postgres-network:
    driver: bridge
