version: '3.5'

services:
  database:
    container_name: mariadb
    restart: always
    image: mariadb
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: db
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha        
    volumes:
    - db-volume:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  db-volume:
