version: '3.5'
services:
    database:
        image: mysql:8
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: q1w2e3r4
            MYSQL_DATABASE: django2
            MYSQL_USER: django2
            MYSQL_PASSWORD: q1w2e3r4
        volumes:
            - db-volume:/var/lib/mysql

volumes:
    db-volume:
